
services:

  db:
    build:
      context: .
      dockerfile: Dockerfile_postgis

  riscosrv:
    build:
      context: .
      dockerfile: Dockerfile_riscosrv

  revprox:
    build:
      context: .
      dockerfile: Dockerfile_caddy

  webapp:
    build:
      context: .
      dockerfile: Dockerfile_webapp
