# syntax=docker/dockerfile:1

FROM golang:1.20-bullseye

ENV GO111MODULE=on
ENV GOFLAGS=-mod=mod

RUN mkdir /app
WORKDIR /app

RUN mkdir log

COPY ./riscosrv_src/ .
COPY ./riscosrv_cfg/ .

RUN go mod download
RUN go mod verify

RUN go build -o riscosrv_v2

# EXPOSE 8020


# command to be used to execute when the image is used to start a container

CMD [ "/app/riscosrv_v2" ]