# syntax=docker/dockerfile:1

# Docker file adapted from postgis/posgis for versions 14-3.2
# RC 11/02/2024

FROM postgres:14-bullseye

LABEL org.opencontainers.image.authors="rpcavaco@gmail.com" 
LABEL org.opencontainers.image.description="PostgreSQL+PostGIS 14-3.4 db container for RISCO Workshop, Feb 2024"

ENV POSTGIS_MAJOR 3
ENV POSTGIS_VERSION 3.4.2+dfsg-1.pgdg110+1

RUN apt-get update \
      && apt-cache showpkg postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR \
      && apt-get install -y --no-install-recommends \
           postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR=$POSTGIS_VERSION \
           postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR-scripts \
      && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /docker-entrypoint-initdb.d

# Create users, work database, grant privileges, add extensions to work databases
COPY ./initdb-postgis.sh /docker-entrypoint-initdb.d/10_postgis.sh

# Create 'risco_v2' schema and fill its structure  
COPY ./sql/risco_pg_deployment.sql /docker-entrypoint-initdb.d/20_risco_pg_deployment.sql
COPY ./sql/risco_v2_cfgdata.sql /docker-entrypoint-initdb.d/30_risco_pg_cfgdata.sql

# Create 'evoradata' schema to hold data samples
COPY ./sql/create_evoradata_schema.sql /docker-entrypoint-initdb.d/40_create_evoradata_schema.sql

# Load data samples
COPY ./sql/evoradata_data.sql /docker-entrypoint-initdb.d/50_evoradata_data.sql


